//go:build linux
// +build linux

// This program demonstrates attaching a fentry eBPF program to
// tcp_close and reading the RTT from the TCP socket using CO-RE helpers.
// It prints the IPs/ports/RTT information
// once the host closes a TCP connection.
// It supports only IPv4 for this example.
//
// Sample output:
//
// examples# go run -exec sudo ./tcprtt
// 2022/03/19 22:30:34 Src addr        Port   -> Dest addr       Port   RTT
// 2022/03/19 22:30:36 10.0.1.205      50578  -> 117.102.109.186 5201   195
// 2022/03/19 22:30:53 10.0.1.205      0      -> 89.84.1.178     9200   30
// 2022/03/19 22:30:53 10.0.1.205      36022  -> 89.84.1.178     9200   28

package main

import (
	"bytes"
	"context"
	"encoding/binary"
	"errors"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/KumKeeHyun/ttcp/internal"
	"github.com/KumKeeHyun/ttcp/server"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/exporters/stdout/stdoutmetric"
	"go.opentelemetry.io/otel/metric/global"
	"go.opentelemetry.io/otel/metric/instrument"
	controller "go.opentelemetry.io/otel/sdk/metric/controller/basic"
	processor "go.opentelemetry.io/otel/sdk/metric/processor/basic"
	"go.opentelemetry.io/otel/sdk/metric/selector/simple"
)

// $BPF_CLANG and $BPF_CFLAGS are set by the Makefile.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc $BPF_CLANG -cflags $BPF_CFLAGS -target bpfel -type event bpf ./bpf/ttcp.c -- -I./bpf/headers

func main() {
	ctx, cancel := signal.NotifyContext(
		context.Background(),
		os.Interrupt,
		syscall.SIGTERM)
	defer cancel()

	InstallStdoutExport(ctx)

	// Allow the current process to lock memory for eBPF resources.
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatal(err)
	}

	objs, bpfClose := startBPFProgram(ctx)
	defer bpfClose()

	startApiServer(ctx, objs)

	<-ctx.Done()
	log.Println(ctx.Err())
}

func InstallStdoutExport(ctx context.Context) func() {
	exporter, err := stdoutmetric.New(stdoutmetric.WithPrettyPrint())
	if err != nil {
		log.Fatalf("creating stdoutmetric exporter: %v", err)
	}

	pusher := controller.New(
		processor.NewFactory(
			simple.NewWithInexpensiveDistribution(),
			exporter,
		),
		controller.WithExporter(exporter),
	)
	if err = pusher.Start(ctx); err != nil {
		log.Fatalf("starting push controller: %v", err)
	}

	global.SetMeterProvider(pusher)

	return func() {
		if err := pusher.Stop(ctx); err != nil {
			log.Fatalf("stopping push controller: %v", err)
		}
	}
}

func startBPFProgram(ctx context.Context) (*bpfObjects, func()) {
	// Load pre-compiled programs and maps into the kernel.
	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}

	link, err := link.AttachTracing(link.TracingOptions{
		Program: objs.bpfPrograms.TcpClose,
	})
	if err != nil {
		log.Fatal(err)
	}

	rd, err := ringbuf.NewReader(objs.bpfMaps.Events)
	if err != nil {
		log.Fatalf("opening ringbuf reader: %s", err)
	}

	log.Printf("%-15s %-6s -> %-15s %-6s %-6s %-10s",
		"Src addr",
		"Port",
		"Dest addr",
		"Port",
		"RTT",
		"BOUND",
	)

	go readLoop(ctx, rd)

	return &objs, func() {
		rd.Close()
		link.Close()
		objs.Close()
	}
}

func readLoop(ctx context.Context, rd *ringbuf.Reader) {
	// bpfEvent is generated by bpf2go.
	var event bpfEvent

	tcpCounter, _ := global.MeterProvider().
		Meter("ttcp.tcp_event").
		AsyncInt64().
		Counter(
			"tcp event",
			instrument.WithUnit("1"),
			instrument.WithDescription("tcp inbound outbound"),
		)

	for {
		select {
		case <-ctx.Done():
			log.Println("readLoop: received cancel, exiting..")
			return
		default:
			record, err := rd.Read()
			if err != nil {
				if errors.Is(err, ringbuf.ErrClosed) {
					log.Println("readLoop: received signal, exiting..")
					return
				}
				log.Printf("reading from reader: %s", err)
				continue
			}

			// Parse the ringbuf event entry into a bpfEvent structure.
			if err := binary.Read(bytes.NewBuffer(record.RawSample), internal.NativeEndian, &event); err != nil {
				log.Printf("parsing ringbuf event: %s", err)
				continue
			}

			log.Printf("%-15s %-6d -> %-15s %-6d %-6d %-10s",
				internal.IntToIP(event.Saddr),
				event.Sport,
				internal.IntToIP(event.Daddr),
				event.Dport,
				event.Srtt,
				bound(&event),
			)

			tcpCounter.Observe(ctx, 1,
				attribute.String("src_endpoint", event.srcEndpoint()),
				attribute.String("dest_endpoint", event.destEndpoint()),
				attribute.Int("rtt", int(event.Srtt)),
				attribute.Bool("inbound", event.inbound()),
			)
		}

	}
}

func (be *bpfEvent) srcEndpoint() string {
	return fmt.Sprintf("%s:%d", internal.IntToIP(be.Saddr), be.Sport)
}

func (be *bpfEvent) destEndpoint() string {
	return fmt.Sprintf("%s:%d", internal.IntToIP(be.Daddr), be.Dport)
}

func (be *bpfEvent) inbound() bool {
	return be.IsInbound != 0
}

func bound(e *bpfEvent) string {
	if e.inbound() {
		return "inbound"
	}
	return "outbound"
}

func startApiServer(ctx context.Context, objs *bpfObjects) {
	store := server.NewMapStore(ctx, objs.bpfMaps.FilterTable)
	httpApi := server.NewHttpApi(store)
	http.HandleFunc("/filter", httpApi.ServeHTTP)

	go func() {
		if err := http.ListenAndServe(":8090", nil); err != nil {
			log.Fatal(err)
		}
	}()
}
